version: '3'

services:
  mongo:
    image: mongo
    restart: always
    container_name: 'mongodb-notekeeper'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: superadmin
    ports: 
      - 27017:27017
